
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EliminarUsuario = 20;
  public static final int Parentesis_c = 22;
  public static final int NuevoFormulario = 28;
  public static final int Parentesis_a = 21;
  public static final int EliminarFormulario = 29;
  public static final int Opciones = 48;
  public static final int Llave_c = 24;
  public static final int Llave_a = 23;
  public static final int Coma = 7;
  public static final int Usuario = 35;
  public static final int Corchete_c = 26;
  public static final int MenorQue = 4;
  public static final int Corchete_a = 25;
  public static final int LoginUsuario = 27;
  public static final int FinSolicitud = 10;
  public static final int Imagen = 59;
  public static final int ParametrosComponente = 68;
  public static final int IDCadena = 66;
  public static final int DosPuntos = 6;
  public static final int CrearUsuario = 18;
  public static final int Boton = 61;
  public static final int TipoRequerido = 64;
  public static final int Resta = 13;
  public static final int FinSolicitudes = 16;
  public static final int Suma = 12;
  public static final int ERROR = 71;
  public static final int Radio = 57;
  public static final int Consultas = 52;
  public static final int CredencialesUsuario = 67;
  public static final int Columnas = 50;
  public static final int ConsultarDatos = 34;
  public static final int String = 2;
  public static final int UsuarioNuevo = 38;
  public static final int Combo = 60;
  public static final int NuevoPassword = 39;
  public static final int ModificarComponente = 32;
  public static final int Requerido = 47;
  public static final int AreaTexto = 55;
  public static final int MayorQue = 5;
  public static final int Alineacion = 46;
  public static final int ParametrosFormulario = 69;
  public static final int ModificarUsuario = 19;
  public static final int Titulo = 41;
  public static final int Exclamacion = 8;
  public static final int URL = 51;
  public static final int TextoVisible = 45;
  public static final int EOF = 0;
  public static final int AgregarComponente = 31;
  public static final int ModificarFormulario = 30;
  public static final int Numero = 70;
  public static final int Fichero = 58;
  public static final int Division = 15;
  public static final int CampoTexto = 54;
  public static final int FechaCreacion = 53;
  public static final int error = 1;
  public static final int TipoAlineacion = 62;
  public static final int UsuarioAntiguo = 37;
  public static final int IniciarSolicitudes = 17;
  public static final int TipoTema = 63;
  public static final int ID = 40;
  public static final int EliminarComponente = 33;
  public static final int Filas = 49;
  public static final int Tema = 43;
  public static final int StringSin = 3;
  public static final int IniciarSolicitud = 9;
  public static final int Password = 36;
  public static final int Checkbox = 56;
  public static final int Igual = 11;
  public static final int Fecha = 65;
  public static final int Clase = 44;
  public static final int Nombre = 42;
  public static final int Multiplicacion = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "String",
  "StringSin",
  "MenorQue",
  "MayorQue",
  "DosPuntos",
  "Coma",
  "Exclamacion",
  "IniciarSolicitud",
  "FinSolicitud",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "FinSolicitudes",
  "IniciarSolicitudes",
  "CrearUsuario",
  "ModificarUsuario",
  "EliminarUsuario",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "LoginUsuario",
  "NuevoFormulario",
  "EliminarFormulario",
  "ModificarFormulario",
  "AgregarComponente",
  "ModificarComponente",
  "EliminarComponente",
  "ConsultarDatos",
  "Usuario",
  "Password",
  "UsuarioAntiguo",
  "UsuarioNuevo",
  "NuevoPassword",
  "ID",
  "Titulo",
  "Nombre",
  "Tema",
  "Clase",
  "TextoVisible",
  "Alineacion",
  "Requerido",
  "Opciones",
  "Filas",
  "Columnas",
  "URL",
  "Consultas",
  "FechaCreacion",
  "CampoTexto",
  "AreaTexto",
  "Checkbox",
  "Radio",
  "Fichero",
  "Imagen",
  "Combo",
  "Boton",
  "TipoAlineacion",
  "TipoTema",
  "TipoRequerido",
  "Fecha",
  "IDCadena",
  "CredencialesUsuario",
  "ParametrosComponente",
  "ParametrosFormulario",
  "Numero",
  "ERROR"
  };
}

